
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "QSnake", email = "jester36883688@gmail.com"},
]
dependencies = [
    "commitizen>=3.5.2",
    "minio>=7.1.15",
    "requests>=2.31.0",
]
requires-python = ">=3.11"
license = {text = "MIT"}
